#!/bin/sh

### BEGIN INIT INFO
# Provides:          analytics
# Required-Start:    $local_fs $network $named
# Required-Stop:     $local_fs $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: UseResponse Analytics Server
# Description:       Server stores the analytics data and maintains analytics queries. Written with Go.
### END INIT INFO

NAME=analytics
DESC=analytics

# Include functions
set -e
. /lib/lsb/init-functions

start() {
  start-stop-daemon -Sbvx /usr/bin/analytics
}

stop() {
  start-stop-daemon -Kvx /usr/bin/analytics
}

status() {
  pid=`pidof -s analytics`
  pid=$((pid - 1 + 1))

  if [ "$pid" -eq 0 ]; then
    echo "Stopped";
  else
    echo "Running...";
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0